targets:
  - entry: src/example.js
    output: example.min.js
  #- entry: src/another.js
  #  output: another.min.js
  #  override:
  #    - src/example.js
source:
  #- src/**/*.js
ignore:
  #- src/**/*_ignore.js
arguments:
  #--language_out: ES5
  #--language_in: ES6
